auto: true
markdown: rdiscount
pygments: true

title: ISLogs

url: http://ostlabs.github.io/islogs/

permalink: /:categories/:title/

author:
    name: Jason Kendall
    email: jakendall@gmail.com
    github: coolacid
    twitter: coolacid

