auto: true
markdown: rdiscount
pygments: true

title: ISLogs

url: http://www.islogs.com

permalink: /:categories/:title/

author:
    name: Jason Kendall
    email: jakendall@gmail.com
    github: coolacid
    twitter: coolacid

