auto: true
markdown: rdiscount
pygments: true

title: ISLogs

url: http://islogs.com

permalink: /:categories/:title/

comments:
    provider: disqus
    disqus:
        short_name: islogscom

author:
    name: ISLogs Team
    email: jakendall@gmail.com
    github: coolacid
    twitter: coolacid

